// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pptzvymwuomjvfnummen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdHp2eW13dW9tanZmbnVtbWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDg1MDgsImV4cCI6MjA2ODgyNDUwOH0.fKWK9bOB2aSyYPTriL5p3opyu42Pz78Go6CJaPOxzM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});